server:
  servlet:
    context-path: /hourcalculator/api
  port: 3001

gab:
  security:
    key: 24352625352516253625363565265365212876512165361253651287365128765123138765213876598790217340987432809432108743210987432108743209870987432109874321874329874321432109843209874320987432098743209874320987432098743210874321098743209874321087432109874321098743210879432874328743208743210987432098743210987432180743209874320874320987432087432087432087432098743209874320987432098743209874320987432098743209873509875132lh432hu432432434324324328z4328z43287432ehzeee3heoiuhoiuhoihewqoihuwoieqfhuwoieqhfoiwq

spring.jpa:
  generate-ddl: true

spring:
  profiles:
    active: prod